### PR TITLE
Don't store state on tree nodes

### LINKED ISSUE #513: There is no response after executing "Azure: Delete Resource Group..." from command palette
**OS:** Win10
**Build Version:** 20230111.7

**Repro Steps:**
1. F1 -> Click "Azure: Delete Resource Group...".
2. Check whether the resource groups are listed.

**Expect:**
The resource groups are listed.

**Actual:**
There is no response after executing "Azure: Delete Resource Group..." from command palette.

### PR DESCRIPTION
**Pull request by alexweininger**
This is a direction I've liked to go in for a while now. But the gist is that we shouldn't be storing state on tree nodes since they are ephemeral. This is even more important now that we aren't caching tree nodes. Instead of storing state on tree items, we can store state centrally mapped to resource ids. And use event emitters to handle updates.

One common case for why this is needed is for commands invoked from the command palette, which then select a resource using a quick pick. For some more context, see https://github.com/microsoft/vscode-azureresourcegroups/issues/487#issuecomment-1376616009. I've added a band aid fix for v1.5 extensions, however moving forward we need a better solution.

The state we store is very simple. It mostly has to do with conveying an action is currently happening to a tree item. Think `runWithTemporaryDescription` kind of stuff. Currently all of this is handled by `AzExtTreeItem`, but now it will be handled by this.

A simplified version of how it works: you can fire an update event for a resource id, tree nodes can listen to this event and refresh themselves if they represent that resource id.

Some of the other benefits to this approach are:
* Only the resource id is needed to apply state updates. This is important for when commands are called from the palette and pick a resource
* State is preserved through refreshes
* State can be applied to all tree items that represent a resource. This means that if we in the future have multiple tree items on the tree that represent the same resource, they both will reflect state changes (if we want).

In the near future when we're rewriting client extensions for v2, I plan on using the same pattern, and making shared utilities for this. For now, I'll keep it in resource groups.

Another note: the reason I'm doing this now is it's required for #513. I will follow this PR up with for #513 and it will show a bit more as to why this is needed.

### CODE REVIEW

File: src/tree/azure/GroupingItem.ts [hunk 1]
```diff
@@ -101,7 +102,7 @@ export class GroupingItem implements ResourceGroupsItem {
         treeItem.iconPath = this.iconPath;
         treeItem.id = this.id;
 
-        return treeItem;
+        return treeItemState.applyToTreeItem({ ...treeItem, id: this.id });
```
Comment (alexweininger) [inline src/tree/azure/GroupingItem.ts:105]: An idea of mine is to find the best way to apply this to all tree items, rather than manually applying it in each `getTreeItem` method.

Possible an abstract base class for tree items, but I'm still working on it.

**Review by nturinski — APPROVED** [review]
