### PR TITLE
Fix delete resource group from command palette

### LINKED ISSUE #466: An error occurs when creating a resource group from Command Palette
**OS:** Win10
**Build Version:** Azure Resources v0.5.7-alpha.0

**Repro Steps:**
F1 -> Azure: Create Resource Group...

**Expect:**
It navigates to next step without any error.

**Actual:**
An error occurs.
image

**More Info:**
1. This issue also reproduces when creating resource group with "Azure: Create Resource..." command.
2. This issue does not reproduce when creating a resource group from context menu.

### LINKED ISSUE #513: There is no response after executing "Azure: Delete Resource Group..." from command palette
**OS:** Win10
**Build Version:** 20230111.7

**Repro Steps:**
1. F1 -> Click "Azure: Delete Resource Group...".
2. Check whether the resource groups are listed.

**Expect:**
The resource groups are listed.

**Actual:**
There is no response after executing "Azure: Delete Resource Group..." from command palette.

### PR DESCRIPTION
**Pull request by alexweininger**
Fixes #513 
Fixes #466

Since the user could have their resources grouped by something other than resource groups, we need to pick resource groups by listing them from the SDK instead of using the tree data provider.

### CODE REVIEW

File: src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts [hunk 1]
```diff
@@ -3,72 +3,110 @@
...
+    // unset nodes that are not resource groups
+    selectedNodes = selectedNodes?.filter(n => !!n.resourceGroup);
+    if (!primaryNode?.resourceGroup) {
+        primaryNode = undefined;
+    }
+
+    let subscription: AzureSubscription;
+    let resourceGroupsToDelete: AzureResource[] = [];
+
     if (!selectedNodes) {
```
Comment (nturinski) [inline src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts:32]: This is a nightmare. I think we may be able to have a wrapper to handle this logic for all of our functions at some point.

File: src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts [hunk 2]
```diff
@@ -3,72 +3,110 @@
...
 import { settingUtils } from '../../../utils/settingUtils';
+import { createSubscriptionContext } from '../../../utils/v2/credentialsUtils';
 import { DeleteResourceGroupContext } from '../DeleteResourceGroupContext';
 import { DeleteResourceGroupStep } from '../DeleteResourceGroupStep';
 
 export async function deleteResourceGroupV2(context: IActionContext, primaryNode?: GroupingItem, selectedNodes?: GroupingItem[]): Promise<void> {
+
+    // unset nodes that are not resource groups
+    selectedNodes = selectedNodes?.filter(n => !!n.resourceGroup);
+    if (!primaryNode?.resourceGroup) {
```
Comment (nturinski) [inline src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts:25]: Is this property unique to resource group resources? I'm pretty sure it exists on other resources. Shouldn't we check the `type` property?

File: src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts [hunk 3]
```diff
@@ -3,72 +3,110 @@
...
-            // TODO: Deal with picker.
-            // const subscription: SubscriptionTreeItem = await ext.appResourceTree.showTreeItemPicker(SubscriptionTreeItem.contextValue, context);
-            // selectedNodes = await subscription.pickResourceGroup(context, {
-            //    canPickMany: true,
-            //    placeholder: localize('selectResourceGroupToDelete', 'Select resource group(s) to delete'),
-            //});
+            ({ subscription, resourceGroupsToDelete } = await pickResourceGroups(context));
         }
     } else {
         selectedNodes = selectedNodes.filter(n => !!n.resourceGroup);
```
Comment (nturinski) [inline src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts:41]: Do `selectedNodes` also include the `primaryNode`? I could see it technically being "selected".

File: src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts (hunk 2 above)
Comment (alexweininger) [reply src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts:25]: Good catch. I don't think it currently exists on items other than the resource groups `GroupingItems`, however I could see this causing a bug in the future if it was added to another item.

I'll do an `instanceof` check as well. I really like avoiding using `instanceof` because it can cause other issues, but it's necessary here for now.

File: src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts (hunk 3 above)
Comment (alexweininger) [reply src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts:41]: I'll test that, regardless it's very confusing 😄

File: src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts (hunk 1 above)
Comment (alexweininger) [reply src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts:32]: Agreed, the whole selected vs primary is pretty confusing.

File: src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts (hunk 2 above)
Comment (nturinski) [reply src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts]: Why not just check for this `"type": "Microsoft.Resources/resourceGroups"?

Comment (alexweininger) [reply src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts]: The object is a `GroupingItem`, not an `AzureResource`.

File: src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts (hunk 3 above)
Comment (alexweininger) [reply src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts]: So yeah. The primary node is whatever node has been right clicked to bring up the context menu. And it is included in the selected nodes array.

File: src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts (hunk 1 above)
Comment (alexweininger) [reply src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts]: I've added a utility to make it not as ugly.

Comment (bwateratmsft) [reply src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts]: Docker has a similar challenge: https://github.com/microsoft/vscode-docker/blob/main/src/utils/multiSelectNodes.ts

When multiple nodes are selected and an action performed on one of them, we simply ignore those for which the action is not valid.

Comment (alexweininger) [reply src/commands/deleteResourceGroup/v2/deleteResourceGroupV2.ts]: Thanks Brandon, I'll file an issue on azuretools to create a shared utility for this stuff. Hopefully we can come up with a few utils that cover everyone's use case.

**Review by nturinski — APPROVED** [review]
